[package]
name = "binary_merkle_tree"
version = "0.1.0"
authors = ["jakeols <jake_ols@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.8.0"
hex-literal = "0.2.1"
rust-crypto = "0.2.36"